name: app_firebase
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  firebase_ui_auth: ^3.0.0
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^2.0.0
  image_picker: ^0.8.7+4
  firebase_storage: 13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutterfire_300x.png
    - assets/dash.png
